### ISSUE TITLE
Partial mock definition can be improved

### ISSUE THREAD

**Issue by mathonsunday** [testdouble/contributing-tests#1]
The definition of partial mock on the Partial Mock page: 

> Put simply, "partial mock" refers to any actual object which has been wrapped or changed to provide artificial responses or verify actual interactions by a test. 

I already have a good intuitive understanding of partial mocks and am thinking about how I'd present them to a beginner. I think this part of the definition could be improved:

> provide artificial responses or verify actual interactions by a test. 

Partial mocks provide artificial responses to some methods and real responses for others. As a result they can or cannot verify actual interactions by a test depending on the method. This is what's bad about them. Theoretically you could construct a partial mock using a mocking library or handrolled but override all the methods with artificial responses. In that case I don't know if it is still considered a partial mock. If so, I can see how creating both an accurate and understandable definition for beginners would be hard. 

I'd prefer this definition

>  Put simply, "partial mock" refers to any actual object which has been wrapped or changed to provide artificial responses to some methods but not others

**Comment by searls** [comment]
Committed. Thanks!
